apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::904233100204:role/project-bedrock-cluster-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::904233100204:user/bedrock-dev-view
      username: bedrock-dev-view
      groups:
        - view-group
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-25T09:04:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "976"
  uid: 1dfd2a56-7ff3-4885-bed7-a0b6e63cc986
