apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-store-ingress
  namespace: retail-app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-06eeb095ee9e07908,subnet-0c147e9a3b03885f5
    alb.ingress.kubernetes.io/tags: Project=karatu-2025-capstone
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:977145922444:certificate/3ffc616b-db2c-4943-bd4f-542c8d93381c
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
  - host: innovatemart-inc.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui
            port:
              number: 80
